---
abstract: 'print a tree of libxml elements'
author:
  - 'Renee Baecker <github@renee-baecker.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-LibXML-TreeDumper
requires:
  Moo: 1.006
  XML::LibXML: 0
  perl: 5.010001
resources:
  bugtracker: http://github.com/reneeb/XML-LibXML-TreeDumper/issues
  homepage: http://github.com/reneeb/XML-LibXML-TreeDumper
  repository: http://github.com/reneeb/XML-LibXML-TreeDumper.git
version: 0.02
